name: Linux Release Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 0.*.*

permissions:
  contents: write

jobs:
  tumbleweed:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Container
        run: |
          cp .github/entrypoint.sh .github/tumbleweed/entrypoint.sh
          docker build -t tumbleweed:latest .github/tumbleweed/
      - name: Start Container
        run: docker run --privileged -v $(pwd):/gh-actions tumbleweed:latest
      - name: Copy to Release folder
        run: mkdir tumbleweed && cp -r build-tumbleweed/* ./tumbleweed
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tumbleweed
          path: ./tumbleweed
  leap:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Container
        run: |
          cp .github/entrypoint.sh .github/leap/entrypoint.sh
          docker build -t leap:latest .github/leap/
      - name: Start Container
        run: docker run --privileged -v $(pwd):/gh-actions leap:latest
      - name: Copy to Release folder
        run: mkdir leap && cp -r build-leap/* ./leap
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: leap
          path: ./leap
  linux:
    needs:
      [tumbleweed, leap]
    runs-on:
      ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Unified all artifacts
        run: |
          mkdir second-brain-${{github.ref_name}}
          cp -r tumbleweed second-brain-${{github.ref_name}}/tumbleweed
          cp -r leap second-brain-${{github.ref_name}}/leap
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: second-brain-${{github.ref_name}}-linux.tar.gz
          path: second-brain-${{github.ref_name}}
      - name: Release to github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref}}
          files: second-brain-${{github.ref_name}}-linux.tar.gz
